//Connection
export const CHANGE_FOR_CONNECTION = "CHANGE_FOR_CONNECTION";
export const SUBMIT_FOR_CONNECTION = "SUBMIT_FOR_CONNECTION";
export const SAVE_API_DATA = "SAVE_API_DATA";

//Project
export const SUBMIT_FORM = "SUBMIT_FORM";
export const SELECT_TAG = "SELECT_TAG";
export const SELECT_MEMBER = "SELECT_MEMBER";
export const HEADER_MEMBER_SELECTION = "HEADER_MEMBER_SELECTION";
