//Connection
export const HANDLE_CHANGE_FOR_CONNECTION = "HANDLE_CHANGE_FOR_CONNECTION";
export const HANDLE_SUBMIT = "HANDLE_SUBMIT";
export const SAVE_API_DATA = "SAVE_API_DATA";

//Project
export const HANDLE_SUBMIT_FOR_PROJECT = "HANDLE_SUBMIT_FOR_PROJECT";
export const SET_SELECTED_TAG = "SET_SELECTED_TAG";
export const HANDLE_MEMBER_SELECTION = "HANDLE_MEMBER_SELECTION";
export const HANDLE_MEMBER_SELECTION_IN_HEADER =
  "HANDLE_MEMBER_SELECTION_IN_HEADER";
